sv:
  use_transform: false
  voxel_resolution: 0.008
  color_importance: 0.2
  spatial_importance: 0.4
  normal_importance: 0.4
  seed_resolution: 0.05
dataset:
  int numClasses: 2
  numFeatures: 6
  minColorRange: 0.0
  maxColorRange: 255.0
  minNormalRange: -1.0
  maxNormalRange: 1.0
workspace:
  sphere:
    x: 0.065
    y: -0.05
    z: 1.1
    radius: 0.60
    threshold: 0.0
  csg_intersect_cuboid:
    x_min: -0.2
    x_max: 0.2
    y_min: -0.25
    y_max: 0.320
    z_min: -0.2
    z_max: 2.0
camera_parameters:
  rgb:
    focal_length:
      x: 570.342
      y: 570.342
    principal_point:
      x: 319.5
      y: 239.5
  depth:
    focal_length:
      x: 570.342
      y: 570.342
    principal_point:
      x: 314.5
      y: 235.5
camera_to_robot_frame_transformation:
  translation :
    x: 0.881
    y: -0.116
    z: 0.84
  rotation :
    x: -0.355109
    y: -0.0260746
    z: 0.957714
    w: 0.0328733
